apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tax-pipeline-run-   # cada ejecución tendrá nombre único
spec:
  pipelineRef:
    name: tax-pipeline              # mismo nombre que pipeline.yaml
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 2Gi
  params:
    - name: repo-url
      value: "https://github.com/<tu-usuario>/tax-calculator.git"
    - name: image-full-name
      value: "us.icr.io/crn-tax-space/tax-calculator:tekton"
