apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-jasmine
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: node:18-alpine
      workingDir: $(workspaces.source.path)
      script: |
        npm ci
        npx jasmine
